# Setup
title: 새싹 개발자 Dam
description: 웹퍼블리셔 과정 수료후 프론트엔드 정진중
url: https://93dam.github.io/
avatar: /images/memain.jpg
paginate: 5
permalink: pretty
cover_image: /images/bg.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: 차온
  card: summary
logo: logo.png
social:
  name: Choi i Dam
  links:
    - https://twitter.com/Cha_on93
    - https://github.com/93dam
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: I Dam CHOI
  url: https://github.com/93dam
  email: choi2dam@gmail.com
